---
- name: Get GitLab Secrets
  block:
    - name: Check if GitLab Secrets file exists
      stat:
        path: "/etc/gitlab/gitlab-secrets.json"
      register: gitlab_secrets_file_path

    - name: Lookup GitLab Secrets file from first node
      slurp:
        path: "/etc/gitlab/gitlab-secrets.json"
      register: gitlab_secrets_slurp
      no_log: true
      when: gitlab_secrets_file_path.stat.exists

    - name: Save GitLab Secrets file contents
      set_fact:
        gitlab_secrets_json: "{{ gitlab_secrets_slurp.content }}"
      when: gitlab_secrets_file_path.stat.exists
      delegate_to: localhost
      delegate_facts: true
      become: false
      no_log: true
  run_once: true
  when: hostvars['localhost'].gitlab_secrets_json is not defined
  tags:
    - reconfigure
    - secrets
    - gitlab-secrets

- name: Write GitLab Secrets
  block:
    - name: Write GitLab Secrets file
      copy:
        content: "{{ (hostvars['localhost'].gitlab_secrets_json | b64decode | from_yaml | to_json(indent=2)) }}"
        dest: "/etc/gitlab/gitlab-secrets.json"
        owner: root
        group: root
        mode: '0600'
      register: gitlab_secrets_file_copy
      no_log: true

    - name: Reconfigure after secrets change if required
      command: gitlab-ctl reconfigure
      register: result
      retries: 3
      until: result is success
      when:
        - gitlab_secrets_file_copy.changed
        - gitlab_secrets_reconfigure
  when:
    - gitlab_secrets_write
    - hostvars['localhost'].gitlab_secrets_json is defined
  tags:
    - reconfigure
    - secrets
    - gitlab-secrets
