# Currently required when adding the secondary site as a standby of the primary site with Patroni.
# Patroni will fail without this due to it already being part of a working cluster, this is the cluster it was using
# as part of its original environment before being added to the Geo deployment.
# Original Error:
# DETAIL:  The primary's identifier is 6903524667333487661, the standby's identifier is 6903523308768856671.
# FATAL:  database system identifier differs between the primary and standby
# Deleting the PostgreSQL data dir and removing the secondaries Patroni cluster resolves this.
# Issue: https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/5872

- name: Patroni Workaround - Stop Patroni on secondary site
  command: |
    gitlab-ctl stop patroni

- name: Patroni Workaround - Delete PostgreSQL data dirs on the secondary site
  file:
    state: absent
    path: /var/opt/gitlab/postgresql/data/

- name: Patroni Workaround - Remove Patroni from existing cluster
  expect:
    command: |
      /opt/gitlab/embedded/bin/patronictl -c /var/opt/gitlab/patroni/patroni.yaml remove postgresql-ha
    responses:
      (.*)Please confirm the cluster name to remove: "postgresql-ha"
      (.*)You are about to remove all information in DCS for postgresql-ha, please type(.*): "Yes I am aware"
      (.*)This cluster currently is healthy. Please specify the master name to continue: "{{ geo_secondary_site_postgres_primary_nodename }}"
    timeout: 60

- name: Patroni Workaround - gitlab-ctl reconfigure
  command: |
    gitlab-ctl reconfigure

- name: Patroni Workaround - Start Patroni on secondary site
  command: |
    gitlab-ctl start patroni
