all:
  vars:
    # Ansible Settings
    ansible_user: "ubuntu"
    ansible_ssh_private_key_file: "{{ lookup('env', 'PWD') }}/../keys/id_ed25519"

    # Cloud Settings, available options: gcp, aws, azure
    cloud_provider: "aws"

    # AWS only settings
    aws_region: "us-east-1"

    # General Settings
    prefix: "demo"
    external_url: "http://44.208.15.49"

    # Passwords / Secrets (Replace values accordingly)
    gitlab_root_password: 'GoGuardians!#1'
    postgres_password: 'GoGuardians!#1'
    consul_database_password: 'GoGuardians!#1'
    gitaly_token: 'GoGuardians!#1'
    pgbouncer_password: 'GoGuardians!#1'
    redis_password: 'GoGuardians!#1'
    praefect_external_token: 'GoGuardians!#1'
    praefect_internal_token: 'GoGuardians!#1'
    praefect_postgres_password: 'GoGuardians!#1'
