---
- name: Clear any previous mounts if not correct server
  block:
    - name: Get existing mount details
      shell: "findmnt --nocanonicalize -o SOURCE -n {{ gitlab_nfs_path }} || echo ''"
      register: existing_mount

    - name: Unmount existing if not correct server
      command: "umount -f -l {{ gitlab_nfs_path }}"
      when:
        - gitlab_nfs_path in existing_mount.stdout
        - gitlab_nfs_int_addr not in existing_mount.stdout

    - name: Remove existing mount config if not correct server
      mount:
        path: "{{ gitlab_nfs_path }}"
        state: absent
      when:
        - gitlab_nfs_path in existing_mount.stdout
        - gitlab_nfs_int_addr not in existing_mount.stdout

- name: Clear any files incorrectly at mount location
  block:
    - name: Check if file exists incorrectly at mount path
      stat:
        path: "{{ gitlab_nfs_path }}"
      register: existing_file_mnt_path

    - name: Remove file if exists incorrectly at mount path
      file:
        path: "{{ gitlab_nfs_path }}"
        state: absent
      when: existing_file_mnt_path.stat.isreg is defined and existing_file_mnt_path.stat.isreg

- name: Mount GitLab NFS
  mount:
    fstype: nfs
    opts: defaults,nofail,lookupcache=positive
    state: mounted
    src: "{{ gitlab_nfs_int_addr }}:{{ gitlab_nfs_path }}"
    path: "{{ gitlab_nfs_path }}"
