---
- hosts: all:!gitlab_*_node_pool:!ungrouped
  become: true
  order: sorted
  roles:
    - common_vars
  vars:
    gcp_service_account_target_file: "/etc/gitlab/serviceaccount.json"
  tasks:
    - name: Remove any unneeded Service Account keys (Omnibus)
      file:
        path: "{{ gcp_service_account_target_file }}"
        state: absent
      when: omnibus_node
