---
gitlab_charts_repo_name: 'gitlab'
gitlab_charts_repo_url: "https://charts.gitlab.io/"

gitlab_charts_show_values: false

# Cloud Provider specific
gcp_backups_service_account_key_file: ""

aws_partition: ""
aws_account: ""

# Default Replica / Pod counts as given by Reference Architectures, calculated by equivalent Gitaly CPU counts
webservice_default_replica_counts:
  '192': 80
  '96': 35
  '48': 20
  '24': 10
  '12': 4
  '4': 3
sidekiq_default_replica_counts:
  '192': 14
  '96': 14
  '48': 14
  '24': 8
  '12': 8
  '4': 4

# Specific overrides for Cluster Autoscaler image tag if default .0 image has issues
cluster_autoscaler_image_tag:
  '1.26': 'v1.26.2'
